redmineUsername: adminUser
redminePassword: <my-password>

databaseType: postgresql
mariadb:
  enabled: false
postgresql:
  enabled: true
  postgresqlDatabase: redmine
  postgresqlUsername: redmine
  postgresqlPassword: safePassword

ingress:
  enabled: true
  certManager: true
  hostname: <dns-name-you-created>
  tls: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt